#:schema node_modules/wrangler/config-schema.json
name = "jfa-manifold_redirect"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "cv.jfa.dev", custom_domain = true },
  { pattern = "landing.jfa.dev", custom_domain = true },
  { pattern = "links.jfa.dev", custom_domain = true },
  { pattern = "cv.jfalava.eu", custom_domain = true },
  { pattern = "www.jfa.dev", custom_domain = true },
]

[observability]
enabled = false

[placement]
mode = "smart"
