import { defineConfig } from "vite-plus";

export default defineConfig({
  lint: {
    plugins: ["eslint", "react", "typescript", "unicorn", "oxc", "import", "promise"],
    categories: {
      correctness: "error",
      suspicious: "warn",
    },
    env: {
      browser: true,
      es2022: true,
    },
    ignorePatterns: ["worker-configuration.d.ts", "**/*.d.ts"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    rules: {
      "typescript/no-explicit-any": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "no-unused-vars": [
        "error",
        {
          vars: "all",
          args: "after-used",
          caughtErrors: "all",
          ignoreRestSiblings: false,
          varsIgnorePattern: "^_",
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "no-undef": "error",
      "no-unreachable": "error",
      "no-dupe-keys": "error",
      "no-dupe-class-members": "error",
      "no-fallthrough": "error",
      "no-duplicate-imports": "error",
      "no-eval": "error",
      "no-debugger": "error",
      "no-console": ["error", { allow: ["warn", "error"] }],
      "no-with": "error",
      "no-proto": "error",
      "no-new-wrappers": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-var": "error",
      "no-param-reassign": "error",
      "no-extend-native": "error",
      "no-func-assign": "error",
      "no-empty-function": "error",
      "no-extra-bind": "error",
      "no-useless-constructor": "error",
      "no-unused-expressions": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      curly: ["error", "all"],
      "no-implicit-coercion": [
        "error",
        {
          boolean: true,
          number: true,
          string: true,
          disallowTemplateShorthand: true,
        },
      ],
      "prefer-const": ["error", { destructuring: "all" }],
      complexity: ["error", 12],
      "max-depth": ["error", 4],
      "max-params": ["error", 5],
      "max-statements": ["error", 40],
      "import/no-duplicates": "error",
      "import/no-mutable-exports": "error",
      "import/no-cycle": "error",
      "import/no-self-import": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-unsafe-type-assertion": "error",
      "typescript/no-unnecessary-type-assertion": "error",
    },
  },
  fmt: {
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    endOfLine: "lf",
    semi: true,
    singleQuote: false,
    trailingComma: "all",
    insertFinalNewline: true,
    experimentalSortPackageJson: {
      sortScripts: true,
    },
    experimentalSortImports: {
      order: "asc",
      newlinesBetween: true,
      internalPattern: ["@/"],
      sortSideEffects: false,
      groups: [
        ["side-effect"],
        ["builtin"],
        ["external", "type-external"],
        ["internal", "type-internal"],
        ["parent", "type-parent"],
        ["sibling", "type-sibling"],
        ["index", "type-index"],
        ["unknown"],
      ],
    },
    ignorePatterns: [
      "cloudflare-env.d.ts",
      "worker-configuration.d.ts",
      ".wrangler/",
      "node_modules/",
    ],
  },
});
