import { createFileRoute, useSearch } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { useMemo } from "react";

import { ServicesTable } from "@/components/services-table";
import serviceSearchArtifact from "@/data/service-search-index.json";
import { importServices } from "@/data/services";
import { CatalogHeader } from "@/features/catalog/components/catalog-header";
import { translations } from "@/features/catalog/lib/translations";
import { hydrateServiceSearchIndex, type SerializedServiceSearchIndex } from "@/lib/service-search";

const getServices = createServerFn({
  method: "GET",
}).handler(async () => await importServices());

interface SearchParams {
  q?: string;
}

export const Route = createFileRoute("/")({
  validateSearch: (search: SearchParams) => ({
    q: search.q ? search.q : undefined,
  }),
  loader: async () => await getServices(),
  component: Home,
});

/** Main services catalog page. */
function Home() {
  const services = Route.useLoaderData();
  const navigate = Route.useNavigate();
  const { q } = useSearch({ from: "/" });
  const activeQuery = q ?? "";
  const t = translations;

  // SAFETY: This checked-in JSON artifact is generated by buildServiceSearchArtifact and consumed with its matching contract.
  const searchIndex = useMemo(
    () =>
      hydrateServiceSearchIndex(services, serviceSearchArtifact as SerializedServiceSearchIndex),
    [services],
  );

  const clearQuery = (): void => {
    void navigate({
      to: "/",
      search: (previous) => ({
        ...previous,
        q: undefined,
      }),
    });
  };

  return (
    <div className="flex h-dvh min-h-0 w-full flex-col overflow-hidden bg-background text-foreground">
      <CatalogHeader
        activeQuery={activeQuery}
        onClearQuery={clearQuery}
        searchIndex={searchIndex}
        services={services}
        t={t}
      />
      <div className="mx-auto flex min-h-0 w-full max-w-screen-2xl flex-1 flex-col overflow-hidden border-x border-border bg-background">
        <main id="services" className="catalog-main min-h-0 flex-1 overflow-hidden">
          <ServicesTable
            translations={t}
            searchQuery={activeQuery}
            searchIndex={searchIndex}
          />
        </main>
      </div>
    </div>
  );
}
