import { preferenceCookies, readPreference, writePreference } from "@jfa.dev/common/preferences";
import { createFileRoute, useSearch } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";

import { ServicesTable } from "@/components/services-table";
import serviceSearchArtifact from "@/data/service-search-index.json";
import { importServices } from "@/data/services";
import { CatalogHeader } from "@/features/catalog/components/catalog-header";
import {
  isLanguageCode,
  translations,
  type LanguageCode,
} from "@/features/catalog/lib/translations";
import { hydrateServiceSearchIndex, type SerializedServiceSearchIndex } from "@/lib/service-search";

const getServices = createServerFn({
  method: "GET",
}).handler(async () => await importServices());

interface SearchParams {
  lang?: string;
  q?: string;
}

export const Route = createFileRoute("/")({
  validateSearch: (search: SearchParams) => ({
    lang: isLanguageCode(search.lang) ? search.lang : undefined,
    q: search.q ? search.q : undefined,
  }),
  loader: async () => await getServices(),
  component: Home,
});

/** Main services catalog page. */
function Home() {
  const services = Route.useLoaderData();
  const navigate = Route.useNavigate();
  const { lang, q } = useSearch({ from: "/" });
  const [cookieLang] = useState<LanguageCode>(() => {
    const savedLanguage = readPreference(preferenceCookies.language);
    return isLanguageCode(savedLanguage) ? savedLanguage : "en";
  });
  const currentLang = lang ?? cookieLang;
  const activeQuery = q ?? "";
  const t = translations[currentLang];

  useEffect(() => {
    if (lang !== undefined) {
      writePreference(preferenceCookies.language, lang);
    }
  }, [lang]);

  useEffect(() => {
    document.documentElement.lang = currentLang;
  }, [currentLang]);

  // SAFETY: This checked-in JSON artifact is generated by buildServiceSearchArtifact and consumed with its matching contract.
  const searchIndex = useMemo(
    () =>
      hydrateServiceSearchIndex(services, serviceSearchArtifact as SerializedServiceSearchIndex),
    [services],
  );

  const clearQuery = (): void => {
    void navigate({
      to: "/",
      search: (previous) => ({
        ...previous,
        q: undefined,
      }),
    });
  };

  return (
    <div className="flex h-dvh min-h-0 w-full flex-col overflow-hidden bg-background text-foreground">
      <CatalogHeader
        activeQuery={activeQuery}
        currentLang={currentLang}
        onClearQuery={clearQuery}
        searchIndex={searchIndex}
        services={services}
        t={t}
      />
      <div className="mx-auto flex min-h-0 w-full max-w-screen-2xl flex-1 flex-col overflow-hidden border-x border-border bg-background">
        <main id="services" className="catalog-main min-h-0 flex-1 overflow-hidden">
          <ServicesTable
            translations={t}
            currentLang={currentLang}
            searchQuery={activeQuery}
            searchIndex={searchIndex}
          />
        </main>
      </div>
    </div>
  );
}
